Repository tomipaul/WeKnow_api, pull requests merged in 2018-08, with the labels that each got.

#30 #159529462 Add and update supertest as internal project package
  collection_test.go
  comment_test.go
  libs/supertest/supertest.go
  libs/supertest/supertest_test.go
  main_test.go
  resource_test.go
Labels: feature, high priority

#31 #154088199 User should be able to get a resource
  app.go
  handler/resource.go
  resource_test.go
Labels: feature

#36 #159423276 Fix bug in resource endpoints
  handler/resource.go
  main_test.go
  resource_test.go
  utilities/validations.go
Labels: bug

#37 #159539338 Update README.md
  .env-sample
  README.md
Labels: chore

#34 #157845495 User should be able to add resource to a collection
  app.go
  collection_test.go
  handler/collection.go
  handler/resource.go
  main_test.go
  migrations/1_initial_setup.go
  migrations/sql.txt
  model/main.go
  model/models.go
  utils_test.go
Labels: feature

#39 #159722371 Refactor and update code to run migrations on deployed apps
  .env-sample
  Gopkg.toml
  Procfile
  app.go
  app.json
  main.go
  migrations/main.go
  migrations/sql.txt
  model/main.go
  utilities/database.go
  utils_test.go
Labels: chore

#38 #159545736 Implement privacy defined restrictions for resource access
  handler/resource.go
  model/models.go
  resource_test.go
  utils_test.go
Labels: feature
